FROM public.ecr.aws/bitnami/spark:3.5

USER root

RUN pip install --quiet \
    delta-spark==2.4.0 \
    scikit-learn==1.4.2 \
    mlflow==2.13.0 \
    pandas==2.2.2 \
    numpy==1.26.4 \
    pytest==8.2.0 \
    python-dotenv==1.0.1

WORKDIR /app
